apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: m2-web-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/xedriq/m2-web-k8s-manifest
    targetRevision: HEAD
    path: prod
  destination: 
    server: https://kubernetes.default.svc
    namespace: m2-web

  syncPolicy:
    syncOptions:
      - CreateNamespace=true    

    automated:
      selfHeal: true
      prune: true
