apiVersion: v1
kind: Service
metadata:
  name: m2-web-service
  labels:
    app: m2-web
spec:
  selector:
    app: m2-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
