apiVersion: apps/v1
kind: Deployment
metadata:
  name: m2-web
  labels:
    app: m2-web
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: m2-web
  template:
    metadata:
      labels:
        app: m2-web
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: mm-admin-v3
        image: zen0hub/m2-web:staging
        ports:
        - containerPort: 3000
        imagePullPolicy: Always

